# Site settings
title: blog.sankichi.net
author:
  name: Takahiro Miyoshi
  url: https://sankichi.net/
  twitter: sankichi92
description: 音楽とSF小説が好きなソフトウェアエンジニアのブログ
lang: ja-JP
google_analytics: UA-29326026-1
date_format: "%Y年%-m月%-d日"

# Build settings
theme: null
markdown: CommonMarkGhPages
commonmark: # Remove `tagfilter` extension from https://github.com/github/pages-gem/blob/919909ac50c197a248ecd293b71feeabcb8ef58d/lib/github-pages/configuration.rb#L153-L156
  extensions: ['table', 'strikethrough', 'autolink']
  options: ['FOOTNOTES']
permalink: /:categories/:title/
plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-sitemap

# jekyll-seo-tag
twitter:
  username: sankichi92
  card: summary
social:
  name: Takahiro Miyoshi
  links:
    - https://twitter.com/sankichi92
    - https://github.com/sankichi92
    - https://www.facebook.com/sankichi9
    - https://www.linkedin.com/in/sankichi92/
