# Site settings
title: ゆとりずむ
email: ""
description: >-
  SFと音楽が好きなWebエンジニアさんきちのブログ
baseurl: ""
url: ""
twitter_username: sankichi92
github_username: sankichi92

# Build settings
timezone: Asia/Tokyo
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
